import { type Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#dca900",
        error: "#ffb4ab",
        "primary-fixed": "#dae2ff",
        "surface-container-low": "#191b23",
        "surface-container-high": "#282a31",
        "on-tertiary-fixed-variant": "#930011",
        primary: "#b2c5ff",
        "on-secondary-fixed-variant": "#5a4400",
        "outline-variant": "#434654",
        "surface-container-highest": "#32343c",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "primary-fixed-dim": "#b2c5ff",
        "on-error": "#690005",
        "surface-bright": "#373941",
        outline: "#8d909f",
        secondary: "#fac52c",
        "tertiary-fixed": "#ffdad6",
        "inverse-surface": "#e1e2ec",
        "on-surface-variant": "#c3c6d6",
        tertiary: "#ffb3ad",
        "on-primary": "#002b73",
        background: "#11131a",
        "tertiary-container": "#ff544f",
        "on-primary-fixed": "#001848",
        "on-primary-container": "#002565",
        "on-secondary-container": "#564000",
        "on-tertiary-fixed": "#410003",
        surface: "#11131a",
        "on-surface": "#e1e2ec",
        "on-tertiary-container": "#5c0007",
        "surface-container-lowest": "#0c0e15",
        "on-tertiary": "#680009",
        "on-primary-fixed-variant": "#0040a1",
        "surface-tint": "#b2c5ff",
        "secondary-fixed-dim": "#f4bf26",
        "inverse-primary": "#1156cd",
        "on-secondary": "#3e2e00",
        "surface-dim": "#11131a",
        "primary-container": "#5b8cff",
        "inverse-on-surface": "#2e3038",
        "on-background": "#e1e2ec",
        "tertiary-fixed-dim": "#ffb3ad",
        "on-secondary-fixed": "#251a00",
        "surface-variant": "#32343c",
        "secondary-fixed": "#ffdf97",
        "surface-container": "#1d1f27",
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        "margin-tablet": "2rem",
        "space-xs": "0.25rem",
        "margin-mobile": "1.25rem",
        gutter: "1.5rem",
        "gutter-mobile": "1rem",
        margin: "4rem",
        "space-md": "1rem",
      },
      fontFamily: {
        "label-md": ["Work Sans", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Work Sans", "sans-serif"],
        "display-xl-mobile": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Work Sans", "sans-serif"],
        "display-xl": ["Space Grotesk", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "label-sm": ["Work Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
} satisfies Config;